security:
 ignored: /**
 basic:
  enabled: false
server:
  port: 8090
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
     ddl-auto: create
      # ddl-auto: create allows us to create schema in our postgres container db     
management:
 security:
  enabled: false
 endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
 metrics:
   distribution:
     percentiles-histogram.http.server.requests: true
     percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999